version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html/   
permissions:
   - object: /usr/share/nginx/html
     pattern: "**"
     owner: root
     group: root
     mode: 755
     type:
       - file
hooks:
  ApplicationStop:
    - location: scripts/stopnginx.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/installnginx.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/startnginx.sh
      timeout: 300
      runas: root
