version: 0.0
os: linux
files:
  - source: public/
    destination: /usr/share/nginx/html/    
hooks:  
  BeforeInstall:
    
    - location: scripts/install_dependencies.sh
      runas: root
      timeout: 300
  
  AfterInstall:
    - location: scripts/restartnginx.sh
      runas: root
