version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html/   
permissions:
  - object: /usr/share/nginx/html/
    owner: root
    group: root
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/installnginx.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/startnginx.sh
      timeout: 300
      runas: root
