version: 0.0
os: linux
files:
  - source: /build/
    destination: /usr/share/nginx/html/    
hooks:  
  ApplicationStop:
    - location: scripts/stopnginx.sh
      timeout: 300
      runas: root
      
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      runas: root
      timeout: 300
  
  AfterInstall:
    - location: scripts/restartnginx.sh
      runas: root
      timeout: 300

