version: 0.0
os: linux
files:
  - source: build/*
    destination: /usr/share/nginx/html/    
hooks:  
  BeforeInstall:
    
    - location: scripts/install_dependencies.sh
      runas: root
      timeout: 300
  
  AfterInstall:
    - location: scripts/restartnginx.sh
      runas: root
   
  ApplicationStop:
    - location: scripts/stopnginx.sh
      timeout: 300
      runas: root
    
    - location: scripts/start-app.sh
      run-as: root

