version: 0.0
os: linux
files:
  - source: /Memoir-App.zip
    destination: /usr/share/nginx/html/   
permissions:
  - object: /usr/share/nginx/html/
    owner: root
    group: root
    mode: 777
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh 
      timeout: 300
      runas: root
