version: 0.2
phases:
    install:
      runtime-versions:
         nodejs: 12
      commands:
         - echo installing Node12.......
         - node --version
         - npm --version
    pre_build:
      commands:
         - echo Installing packages
         - npm ci

    build:
      commands:
         - echo Building App
         - npm run build
  
artifacts:
    files:
      - "**/*"
    discard-paths: no
    base-directory: build

