version: 0.2

Phases:
    install:
      runtime-versions:
         nodejs: 14
      commands:
         - echo installing Node14
         - apt-get install curl 
         - curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
         - apt-get install -y nodejs 
         - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
         - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
         - apt-get install -y yarn
    build:
      commands:
         - echo Testing
         - yarn test
         - echo Building App
         - yarn build
artifacts:
    files:
      - "**/*"
    discard-paths: no
    base-directory: dist
