version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html/   
permissions:
  - object: /usr/share/nginx/html/
    owner: root
    group: root
    mode: 777
    type: file
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh 
      timeout: 100
      runas: root
  AfterInstall:
    - location: scripts/startnginx.sh    
      timeout: 100
      runas: root
  ApplicationStart:
    - location: scripts/restartnginx.sh
      timeout: 100
      runas: root
